### ISSUE TITLE
花价查询功能，更换地图后未能按已选择的花种类过滤，仍显示全部种类

### ISSUE THREAD

**Issue by elicassion** [JX3BOX/app#19]
如图所示
![before](https://user-images.githubusercontent.com/11537907/100834099-49bf8300-3439-11eb-8ff4-5e1251948240.png)
---------------------点击更换地图后------------------------------
![after](https://user-images.githubusercontent.com/11537907/100834101-49bf8300-3439-11eb-8d9d-b0e56e3a32b5.png)

希望更换地图后也能保持花种类过滤不变，谢谢

**Comment by iRuxu** [comment]
#0d37047
感谢建议，已处理
