### ISSUE TITLE
【镇派模拟器】优化项

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/app#34]
![image](https://user-images.githubusercontent.com/8476969/127288230-4a290e14-d14b-4c8b-8650-b132eed00829.png)
当为0层时，显示数字0

---------------------

- [x] 已完成

**Comment by iRuxu** [comment]
总total数，要放在json中，防止后续变动。

-----------

- [ ] 已完成

**Comment by Kaviilee** [comment]
pop新增最高层数

-------------------
- [ ] 已完成

**Comment by Kaviilee** [comment]
children 实现

-----------------------
- [ ] 已完成
